services:
  - type: web
    name: fundme-angola
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile

databases:
  - name: fundme-db
    databaseName: fundme_angola
    user: fundme_user
    plan: free
